post/api/urls.py
from django.urls import path, include
from . import views

app_name = 'post-api'

urlpatterns = [
	path('', views.PostListAPIView.as_view(), name='list'),
	path('<int:pk>/', views.PostDetailAPIView.as_view(), name = 'detail'),
	path('<int:pk>/edit/', views.PostUpdateAPIView.as_view(), name = 'edit'),
	path('<int:pk>/delete/', views.PostDeleteAPIView.as_view(), name = 'delete'),
	path('create/', views.PostCreateAPIView.as_view(), name = 'create'),
]

post/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
	path('', views.index, name = 'index'),
	path('newpost/', views.create, name = 'create'),
	path('<slug:slug>/', views.details, name = 'details'),
	path('<int:pk>/edit/', views.edit, name = 'edit'),
	path('<int:pk>/delete/', views.delete, name = 'delete'),
]

pro_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from post import views

urlpatterns = [
    path('',views.home),
    path('admin/', admin.site.urls),
    path('post/', include('post.urls')),
    path('profile/', include('profile.urls')),
    path('api/post/', include('post.api.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

profile/urls.py
from django.urls import path
from . import views

app_name = 'profile'

urlpatterns = [
	path('<int:pk>', views.profile, name = 'profile'),
	path('<int:pk>/follow/', views.follow, name = 'follow'),
	path('<int:pk>/unfollow/', views.unfollow, name = 'unfollow'),
	path('login/', views.loginUser, name = 'login'),
	path('register/', views.register, name = 'register'),
	path('logout/', views.logoutUser, name = 'logout'),
]

post/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils.text import slugify

# Create your models here.
class PostManager(models.Manager):
	def published(self):
		return super().all().filter(draft=False)

def post_image(instance, filename):
	return 'post/%s/%s' % (instance.slug,filename)

class Post(models.Model):
	author = models.ForeignKey(User, on_delete=models.CASCADE)
	title = models.CharField(max_length = 500)
	content = models.TextField()
	image = models.ImageField(upload_to=post_image, null=True, blank = True, width_field = 'image_width', height_field = 'image_height')
	image_height = models.IntegerField(default = 0)
	image_width = models.IntegerField(default = 0)
	slug = models.SlugField(unique=True)
	created = models.DateTimeField(auto_now = False, auto_now_add = True)
	updated = models.DateTimeField(auto_now = True, auto_now_add = False)
	draft = models.BooleanField(default=False)

	objects = PostManager()

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('post:details', kwargs = {'slug':self.slug})

	def save(self, *args, **kwargs):
		if not self.id:
			self.slug = slugify(self.title)
		super().save(*args, **kwargs)

	class Meta:
		ordering = ['-updated','-created']

profile/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
def profile_picture(instance, filename):
	return 'profile_pic/%s/%s' % (instance.user.username, filename)

def cover_picture(instance, filename):
	return 'cover_pic/%s/%s' % (instance.user.username, filename)

class UserProfile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	profile_pic = models.ImageField(upload_to=profile_picture, default= 'profile_pic/profile_pic.png')
	cover_pic = models.ImageField(upload_to=cover_picture, default= '1.jpg')
	website = models.URLField(null=True, blank = True)
	date_of_birth = models.DateField(null=True, blank=True)
	bio = models.TextField(null=True, blank=True)
	follows = models.ManyToManyField('self', blank=True, related_name='followed_by', symmetrical=False)

	def __str__(self):
		return self.user.username

post/forms.py
from django import forms
from .models import Post

class PostModelForm(forms.ModelForm):

	class Meta:
		model = Post
		fields = ('title', 'content', 'draft', 'image')

profile/forms.py
from django import forms
from .models import UserProfile
from django.contrib.auth import models

class UserProfileModelForm(forms.ModelForm):
	class Meta:
		model = UserProfile
		fields = ('profile_pic','cover_pic', 'bio', 'website', 'date_of_birth')


class RegisterForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)
	class Meta:
		model = models.User
		fields = ['username','first_name', 'last_name','email','password']

class LoginForm(forms.Form):
	username = forms.CharField(max_length=100)
	password = forms.CharField(widget=forms.PasswordInput)

post/api/views.py
from django.db.models import Q

from rest_framework.generics import (
	ListAPIView,
	RetrieveAPIView,
	UpdateAPIView,
	DestroyAPIView,
	CreateAPIView,
	RetrieveUpdateAPIView,
	)
from rest_framework.filters import OrderingFilter

from post.models import Post 
from rest_framework.permissions import IsAuthenticated
from .permissions import IsOwnerOrReadOnly
from .serializers import PostListSerializer, PostDetailSerializer, PostCreateSerializer

class PostCreateAPIView(CreateAPIView):
	queryset = Post.objects.all()
	serializer_class = PostCreateSerializer
	permission_classes = [IsAuthenticated]

	def perform_create(self, serializer):
		serializer.save(author = self.request.user)


class PostListAPIView(ListAPIView):
	queryset = Post.objects.all()
	serializer_class = PostListSerializer
	filter_backends = (OrderingFilter,)
	ordering_fields = ('title', 'author')

	def get_queryset(self, *args, **kwargs):
		queryset_list = super().get_queryset(*args, **kwargs)
		query = self.request.GET.get('search')
		if query:
			queryset_list = queryset_list.filter(
				Q(content__icontains = query) |
				Q(title__icontains = query) |
				Q(author__username = query)	|
				Q(author__first_name__icontains = query) |
				Q(author__last_name__icontains = query)
				).distinct()

		return queryset_list

class PostDetailAPIView(RetrieveAPIView):
	queryset = Post.objects.all()
	serializer_class = PostDetailSerializer

class PostUpdateAPIView(RetrieveUpdateAPIView):
	queryset = Post.objects.all()
	serializer_class = PostDetailSerializer
	permission_classes = [IsAuthenticated, IsOwnerOrReadOnly]

class PostDeleteAPIView(DestroyAPIView):
	queryset = Post.objects.all()
	serializer_class = PostDetailSerializer
	permission_classes = [IsAuthenticated, IsOwnerOrReadOnly]

post/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from django.http import Http404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import PostModelForm
from .models import Post
from profile.models import UserProfile
from django.db.models import Q

def home(request):
	return redirect('post:index')

def index(request):
	queryset = Post.objects.published()
	profiles = UserProfile.objects.all()
	if request.user.is_authenticated:
		profiles = UserProfile.objects.all().exclude(user=request.user)
		queryset = queryset.exclude(author=request.user)
		following_posts = queryset.filter(
			author__in = request.user.userprofile.follows.all().values_list('user',flat=True)
			)
		if not request.GET:
			queryset = following_posts
		elif request.GET.get('post') == 'allpost':
			queryset = queryset
			paginator = Paginator(queryset, 5)
			page = request.GET.get('page')
			context = {'posts': paginator.get_page(page), 'profiles': profiles}
			return render(request, 'post/index.html', context)
		elif request.GET.get('search'):
			queryset = queryset.filter(
				Q(content__icontains = request.GET.get('search')) |
				Q(title__icontains = request.GET.get('search')) |
				Q(author__username = request.GET.get('search'))	|
				Q(author__first_name__icontains = request.GET.get('search')) |
				Q(author__last_name__icontains = request.GET.get('search'))
				).distinct()

	context = {'posts': queryset, 'profiles': profiles}
	return render(request, 'post/index.html', context)

def details(request, slug):
	post = get_object_or_404(Post, slug=slug)
	if post.draft:
		if request.user != post.author and not request.user.is_authenticated:
			raise Http404
	return render(request, 'post/details.html', {'post':post})


@login_required(login_url="profile:login")
def create(request):
	form = PostModelForm(request.POST or None, request.FILES or None)
	if request.method == "POST":
		if form.is_valid():
			newPost = form.save(commit = False)
			newPost.author = request.user
			newPost.save()
			messages.success(request, 'Post Created.')
			return redirect('post:details', slug = newPost.slug)

	return render(request, 'post/create.html', {'form':form})


@login_required(login_url="profile:login")
def edit(request, pk):
	instance = get_object_or_404(Post, pk = pk)
	if request.user != instance.author:
		return redirect('post:details', slug = instance.slug)
	form = PostModelForm(request.POST or None, request.FILES or None, instance = instance)
	if request.method == "POST":
		if form.is_valid:
			post = form.save(commit=False)
			post.save()
			messages.success(request, 'Post updated.')
			return redirect('post:details', slug = post.slug)

	return render(request, 'post/edit.html', {'form': form})

@login_required(login_url="profile:login")
def delete(request, pk):
	post = get_object_or_404(Post, pk= pk)
	if request.user != post.author:
		return redirect('post:details', slug = post.slug)
	post.delete()
	messages.success(request, 'Post deleted.')
	return redirect('post:index')

profile/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .forms import LoginForm, RegisterForm, UserProfileModelForm
from .models import UserProfile
from django import forms


# Create your views here.
def profile(request, pk):
	profile = get_object_or_404(UserProfile, pk=pk)
	posts = profile.user.post_set.published()
	context = {'profile':profile, 'posts':posts}
	if request.user == profile.user:
		form = UserProfileModelForm(request.POST or None, request.FILES or None, instance=profile)
		if request.method == 'POST':
			if form.is_valid():
				instance = form.save(commit=False)
				instance.save()
		posts = profile.user.post_set.all()
		context = {'profile':profile, 'form':form, 'posts':posts}
	return render(request, 'profile/profile.html', context)

@login_required(login_url="profile:login")
def follow(request, pk):
	user = request.user
	profile = get_object_or_404(UserProfile, pk=pk)
	if user != profile.user:
		user.userprofile.follows.add(profile)	
	return redirect('profile:profile', pk=pk)


@login_required(login_url="profile:login")
def unfollow(request, pk):
	user = request.user
	profile = get_object_or_404(UserProfile, pk=pk)
	if user != profile.user and profile in user.userprofile.follows.all():
		user.userprofile.follows.remove(profile)	
	return redirect('profile:profile', pk=pk)


def loginUser(request):
	form = LoginForm(request.POST or None)
	if request.method == 'POST':
		if form.is_valid():
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			user = authenticate(request, username=username, password = password)
			if user is not None:
				if user.is_active:
					login(request, user)
					return redirect(request.GET.get('next') or 'post:index')
			else:
				form.add_error(None, 'Invalid login or password. Please try again!')
	return render(request, 'profile/login.html', {'form':form})



def register(request):
	form = RegisterForm(request.POST or None)
	if request.method == 'POST':
		if form.is_valid:
			instance = form.save(commit=False)
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			instance.set_password(password)
			instance.save()
			user = authenticate(request, username=username, password = password)
			UserProfile.objects.create(user=user)
			if user is not None:
				if user.is_active:
					login(request, user)
					return redirect('post:index')
	return render(request, 'profile/register.html', {'form':form})

@login_required(login_url="profile:login")
def logoutUser(request):
	logout(request)
	return redirect('post:index')

post/templates/post/base.html
<!doctype html>
<html lang="en">
  <head>
  	{% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'post/css/style.css' %}">

    <title>Post</title>
  </head>
  <body>
    <div class="container-fluid m-0 p-0">
    <!-- Navbar -->
      <nav class="navbar navbar-expand-md navbar-light bg-nav">
        <a class="navbar-brand ml-5 font-weight-bold" href="/post/">Post</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto mr-5">
            <li class="nav-item">
              <a class="nav-link" href="/post/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">About</a>
            </li>
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'profile:profile' user.userprofile.id %}">Profile</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'post:create' %}">New Post</a>
              </li>
              <li class="nav-item">
              <a class="nav-link" href="{% url 'profile:logout' %}">LogOut</a>
              </li>
              {% else %}
              <li class="nav-item">
              <a class="nav-link" href="{% url 'profile:login' %}">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'profile:register' %}">Register</a>
              </li>
              {% endif %}
            
          </ul>
          <form class="form-inline my-2 my-lg-0" method='GET' action = '{% url "post:index" %}'>
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name='search' value='{{ request.GET.search }}'>
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
              </form>
        </div>
      </nav>
    <!-- content -->
    {% include 'post/messages.html' %}
    {% block content %}{% endblock %}

    <!-- Fotter -->
    <div class="container-fluid mt-3 footer py-5">
      <div class="row mx-auto">
        <div class="col-md-5 col-sm-6 offset-md-1">
          <div class="h4 my-2">
            About
          </div>
          <div style="color: #c1c1c1!important" class="pb-1">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
            consequat.
          </div>
        </div>
        <div class="col-md-5 col-sm-6">
          <div class="h4 my-2">
            About
          </div>
          <div style="color: #c1c1c1!important" class="pb-1">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
            consequat.
          </div>
        </div>
      </div>
    </div>
  </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

post/templates/post/create.html
{% extends 'post/base.html' %}
{% load static %}

{% block content %}
<div class="container">
	<div class="col-md-8 offset-md-2">
		<div class="my-5 p-5 form-box">
			<form method="POST" enctype="multipart/form-data">
				{% csrf_token %}
				{{ form.as_p }}
				<input type="submit" name="" value = 'Create new post' class='btn btn-primary'>
			</form>	
		</div>
	</div>
</div>

{% endblock%}

post/templates/post/details.html
{% extends 'post/base.html' %}
{% load static %}

{% block content %}
	

		<div class="container my-5">
			<div class="col-md-8 col-sm-10 offset-md-2 offset-sm-1">
				<div class="h3">
					{{ post.title }}
				</div>
				<p class="post-hint">
					{% if post.author.get_full_name %}Author: <a href="{% url 'profile:profile' post.author.userprofile.id %}">{{ post.author.get_full_name }}</a><br>{% endif %}
					{{ post.updated }}
					{% if post.draft %} 
					  <span class="text-danger m-0" style="border: 1px solid red;border-radius: 0.2rem; padding-right: 0.1rem">
					    Draft
					  </span>
					{% endif %}
				</p>
				<div class="col-lg-6 col-md-8 col-sm-10 col-12 pl-0">
					{% if post.image %}
					<img src="{{ post.image.url }}" class="img-fluid">
					{% endif %}
				</div>
				<div class="text">
					{{ post.content }}
				</div>
				{% if user.is_authenticated and user == post.author %}
				<a href="{% url 'post:edit' post.id %}"><button class="btn btn-success">Edit</button></a>
				<a href="{% url 'post:delete' post.id %}"><button class="btn btn-danger">Delete</button></a>
				{% endif %}

			</div>
			
		</div>


{% endblock %}

post/templates/post/index.html
{% extends "post/base.html" %}
{% load static %}
    <!-- content -->
{% block content %}
    <div class="container mt-5">
      <div class="row">

        {% if user.is_authenticated and not request.GET.search %}
        <div class="col-12">
          <a href="?">From your followings</a>
          <a href="?post=allpost&page={{ posts.number }}" class='ml-3'>All Posts</a>
        </div>
        {% endif %}
        <div class="col-12">
          {% if not posts %}
            {% if request.GET.search %}
              No Search result found.
            {% elif user.is_authenticated and not user.userprofile.follows.all %}
              <div class="text-muted mt-3">Follow other author to view there posts here.</div>
              <div class="row">
                {% for profile in profiles %}
                <div class="col-sm-7 profileClass row p-2 my-2">
                  <div class="col-sm-3 col-4">
                    <div>
                      {% if profile.profile_pic %}
                      <img src="{{ profile.profile_pic.url }}" width=100% class = 'img-thumb'></img>
                      {% endif %}
                    </div>
                  </div>
                  <div class="col-sm-9 col-8">
                    <div class="h5">
                      {{ profile.user.get_full_name }}
                      <div class="text-muted mt-0 h5">
                        @{{ profile.user.username }}
                      </div>
                    </div>
                    <div class="text-muted m-0">{{ profile.follows.all.count }} Following 
                    {{ profile.followed_by.all.count }} Followers</div>
                     {% if user != profile.user and profile not in user.userprofile.follows.all %}
                      <a href="{% url 'profile:follow' profile.id %}">Follow</a>
                     {% elif profile in user.userprofile.follows.all %}
                      Followed 
                      <a href="{% url 'profile:unfollow' profile.id %}">Unfollow</a>
                     {% endif %}
                     {% if profile.website %}
                     <div class="text-muted">
                      {{ profile.website }}</div>
                     {% endif %}
                     {% if profile.date_of_birth %}
                     <div class="text-muted">
                      {{ profile.date_of_birth }}</div>
                     {% endif %}
                  </div>
                </div>
                {% endfor %}
              </div>
            {% endif %}
          {% endif %}
        </div>
        <div class="col-sm-9 mx-auto">
          <div class="row">
            <div class="col-12">
              {% for post in posts %}
              <div class="post pb-3 mb-3">
                <div class="h3">
                  {{ post.title }} 
                </div>
                <p class="post-hint">
                  {% if post.author.get_full_name %}Author: <a href="{% url 'profile:profile' post.author.userprofile.id %}">{{ post.author.get_full_name }}</a><br>{% endif %}
                  {{ post.updated }}
                  {% if post.draft %} 
                    <span class="text-danger m-0" style="border: 1px solid red;border-radius: 0.2rem; padding-right: 0.1rem">
                      Draft
                    </span>
                  {% endif %}
                </p>
                {% if post.image %}
            <div class="row">
              <div class="col-md-6">
                <img src="{{ post.image.url }}" class="img-fluid">  
              </div>
              <div class="col-md-6">
                <div class="text-muted my-2">
                  {{ post.content|truncatechars:200 }}
                </div>
                <a href="{{ post.get_absolute_url }}"><button class="btn btn-primary">More</button></a>
              </div>
            </div>

            {% else %}
            <div class="text-muted my-2">
              {{ post.content|truncatechars:200 }}
            </div>
            <a href="{{ post.get_absolute_url }}"><button class="btn btn-primary">More</button></a>
          {% endif %}
          </div>
              {% endfor %}
              {% if posts and request.GET.post %}
              <div class="pagination">
                  <span class="step-links">
                      {% if posts.has_previous %}
                          <a href="?post=allpost&page=1">&laquo; first</a>
                          <a href="?post=allpost&page={{ posts.previous_page_number }}">previous</a>
                      {% endif %}

                      <span class="current">
                          Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
                      </span>

                      {% if posts.has_next %}
                          <a href="?post=allpost&page={{ posts.next_page_number }}">next</a>
                          <a href="?post=allpost&page={{ posts.paginator.num_pages }}">last &raquo;</a>
                      {% endif %}
                  </span>
              </div>
              {% endif %}
            </div>
          </div>
        </div>
        <div class="col-sm-3 col">
          <div style="border-left: 1px outset #e4d5db7d !important" class="pl-1">
            
          </div>
      </div>
    </div>
  </div>
{% endblock %}

post/templates/post/profile.html
{% extends 'post/base.html' %}
{% load static %}

{% block content %}
	

		<div class="container my-5">
			<div class="col-md-8 col-sm-10 offset-md-2 offset-sm-1">
				
				<div class="row">
					<div class="col-sm-4">
						{% if profile.profile_pic %}
						<img src="{{ profile.profile_pic.url }}" class="img-thumbnail"></img>
						{% endif %}
					</div>
					<div class="col-sm-8">
						<div class="h2">
							{{ profile.user.get_full_name }}
							<div class="text-muted mt-0 h5">
								@{{ profile.user.username }}
							</div>
						</div>
						<div class="text-muted m-0">{{ profile.follows.all.count }} Following 
						{{ profile.followed_by.all.count }} Followers</div>
						 {% if user != profile.user and profile not in user.userprofile.follows.all %}
						 	<a href="{% url 'post:follow' profile.id %}">Follow</a>
						 {% elif profile in user.userprofile.follows.all %}
						 	Followed 
						 	<a href="{% url 'post:unfollow' profile.id %}">Unfollow</a>
						 {% endif %}
						 {% if profile.website %}
						 <div class="text-muted">
						 	{{ profile.website }}</div>
						 {% endif %}
						 {% if profile.date_of_birth %}
						 <div class="text-muted">
						 	{{ profile.date_of_birth }}</div>
						 {% endif %}
					</div>
				</div>
				<hr>
				<div class="row">
					<div class="col-12">
					<ul class="nav nav-tabs" id="myTab" role="tablist">
					  <li class="nav-item">
					    <a class="nav-link active" id="post-tab" data-toggle="tab" href="#post" role="tab" aria-controls="post" aria-selected="true">Post</a>
					  </li>
					  <li class="nav-item">
					    <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false">
					    {% if user == profile.user %}
					    	Profile Info
					    {% else %}
					        About Author
					    {% endif %} 	
					    </a>
					  </li>
					  {% if user == profile.user %}
					  <li class="nav-item">
					    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Edit Profile</a>
					  </li>
					  {% endif %} 
					</ul>
				</div>
					<div class="tab-content" id="myTabContent">
					<!-- Post Tab -->
					  <div class="tab-pane fade show active" id="post" role="tabpanel" aria-labelledby="post-tab">
					
					  	{% for post in posts %}

					  	<div class="post pb-3 mb-3 mt-3">
					  	  <div class="h5">
					  	    {{ post.title }} 
					  	  </div>
					  	  <p class="post-hint">
					  	    {{ post.updated }}
					  	    {% if post.draft %} 
					  	      <span class="text-danger m-0" style="border: 1px solid red;border-radius: 0.2rem; padding-right: 0.1rem">
					  	        Draft
					  	      </span>
					  	    {% endif %}
					  	  </p>
					  	  
					  	  {% if post.image %}
					  	  <div class="row mt-3">
					  		  <div class="col-md-6">
					  		    <img src="{{ post.image.url }}" class="img-fluid">  
					  		  </div>
					  		  <div class="col-md-6">
					  		  	<div class="text-muted my-2">
					  		  	  {{ post.content|truncatechars:200 }}
					  		  	</div>
					  		  	<a href="{{ post.get_absolute_url }}"><button class="btn btn-primary">More</button></a>
					  		  </div>
					  	  </div>

					  	  {% else %}
					  	  <div class="text-muted my-2">
					  	    {{ post.content|truncatechars:200 }}
					  	  </div>
					  	  <a href="{{ post.get_absolute_url }}"><button class="btn btn-primary">More</button></a>
					  	{% endif %}
					  	</div>
					  	{% endfor %}
					  </div>
					  	<!-- Profile Tab -->
					  <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
					  	<div class="row mt-3">
					  		<div class="col-sm-4">
					  			{% if profile.profile_pic %}
					  			<img src="{{ profile.profile_pic.url }}" class="img-thumbnail"></img>
					  			{% endif %}
					  		</div>
					  		<div class="col-sm-8">
					  			{% if user == profile.user %}
					  			<form method="POST" enctype="multipart/form-data">
					  				{% csrf_token %}
					  				{{ form.as_p }}
					  				<input type="submit" name="" value = 'Change' class='btn btn-success'>
					  			</form>
					  			{% endif %}
					  		</div>
					  	</div>
					  </div>
					  <!-- About Tab -->
					  <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">
					  	 {% if profile.bio %}
						 <div class="text-muted mt-3">
						 	{{ profile.bio }}</div>
						 {% endif %}
					  </div>
					</div>

				</div>

			</div>
			
		</div>


{% endblock %}